import { UploadUserFile } from 'element-plus'

export const canvasState = () => ({
  fileList: [] as UploadUserFile[],
  canvasInstances: [] as { canvas: any, activeLayerIndex: number }[],
  pagesCount: [1] as number[],
  canvasHistory: [] as any[],
  canvasHistoryIndex: -1,
  zoomLevel: 100,
  pageWidth: 1300,
  pageHeight: 507,
  idPage: 0,
  activePageIndex: 0,
  isObjectSelected: false,
  selectedObjectColor: '',
  selectedObjectType: '',
  selectedObjectAtFront: false,
  selectedObjectAtBack: false,
  selectedFont: null,
  fontSize: 30,
  selectedTextAlign: 'center',
  selectedTextBold: false,
  selectedTextUnderline: false,
  selectedTextItalic: false,
  selectedTextStrikethrough: false,
  selectedLineHeight: 100,
  selectedLetterSpace: 0,
  selectedTextStroke: 1,
  selectedTextStrokeColor: "",
  selectedTextBackgroundColor: '',
  selectedBackgroundPadding: 0,
  selectedBackgroundCornerRadius: 0,
  selectedShadowColor: '',
  selectedShadowOffSetX: 5,
  selectedShadowOffSetY: 5,
  selectedShadowBlur: 0,
  selectedBlur: 0,
  selectedBrightness: 0,
  selectedSepia: false,
  selectedGrayscale: true,
  selectedAnimationDuration: 1,
  selectdElevationAnimationInitialTop: 0,
  selectdElevationAnimationFinalTop: 0,
  selectdElevationAnimationInitialLeft: 0,
  selectdElevationAnimationFinalLeft: 0,
  selectedVisibility: true,
  mediaRecorder: null,
  canvasAnimations: [],
  selectedLock: false,
  removedPagesCount: [],
  selectedOpacity: 1,
  changeSelected: false,
  selectedCornerRadius: 0,
  clonedObject: null,
  selectedAngle: 0,
})
